<template><h1 id="在线万能查询和在线工具-时效未知" tabindex="-1"><a class="header-anchor" href="#在线万能查询和在线工具-时效未知" aria-hidden="true">#</a> 在线万能查询和在线工具（时效未知）</h1>
<ol>
<li>虫部落引擎大全（搜索）：http://search.chongbuluo.com/</li>
<li>虫部落引擎大全（云盘）：http://magnet.chongbuluo.com/</li>
<li>虫部落引擎大全（学术）：http://scholar.chongbuluo.com/</li>
<li>虫部落引擎大全（数据挖掘）：http://data.chongbuluo.com/</li>
<li>虫部落引擎大全（图片）：http://image.chongbuluo.com/</li>
<li>虫部落引擎大全（404Bus）：http://www.404car.com/</li>
<li>Google简体中文1（搜索镜像）：https://coderschool.2345.ga/</li>
<li>Google简体中文2（搜索镜像）：https://g.codery.ga/</li>
<li>Google简体中文3（搜索镜像）：https://google.90h6.cn:1668/</li>
<li>Google简体中文4（学术镜像）：https://scholar.uulucky.com/</li>
<li>Google简体中文5（学术镜像）：https://g.abcdocker.com/scholar</li>
<li>维基百科中文语言1（镜像）：【备用网址1】 【备用网址2】</li>
<li>维基百科中文语言2（镜像）：https://weiji.ga/</li>
<li>维基百科中文语言3（镜像）：https://wikipedia.kfd.me/</li>
<li>维基百科中文语言4（镜像）：https://wiki.4o4.click/</li>
<li>维基百科中文语言5（镜像）：https://wiki.zhtube.com/</li>
<li>维基百科中文语言6（镜像）：https://zhwiki.joshu.moe/</li>
<li>维基百科中文语言7（镜像）：https://zh.mdzz.men/</li>
<li>维基百科中文语言8（镜像）：https://zh.100ke.info/</li>
<li>维基百科中文语言9（创软镜像）：https://w.sxisa.org/</li>
<li>查询IP（1）：https://www.ipip.net/ip.html</li>
<li>查询IP（2）：http://ip.rtbasia.com/</li>
<li>查询IP（3）：http://www.hao7188.com/</li>
<li>查询IP（4）：http://www.ip138.com/ips1388.asp</li>
<li>查询IP（5）：http://ip111.cn/</li>
<li>查询IP（6）：http://myip.cx/</li>
<li>查询手机归属地（1）：http://www.ip138.com/sj/</li>
<li>查询手机归属地（2）：http://cn.m.chahaoba.com/index.php?</li>
<li>查询手机归属地（3）：http://shouji.niuchaxun.com/</li>
<li>查询身份证（1）：http://shenfenzheng.bajiu.cn/</li>
<li>查询身份证（2）：http://idcard.niuchaxun.com/</li>
<li>查询身份证（3）：http://tool.114la.com/live/idcard/</li>
<li>查询交通违章（1）：http://www.ip138.com/weizhang.htm</li>
<li>查询交通违章（2）：https://wxcity.fundway.net:8088/Traffic/ViolationByVehicleLicense</li>
<li>查询交通违章（3）：http://chaxun.weizhang8.cn/</li>
<li>查询交通违章（4）：http://wx.fsga.gov.cn/fsweixin/carframe/carFrameQuery.jsp?key=96f392f3-41cb-4af0-8143-2b34628a2fb4&amp;from=groupmessage&amp;isappinstalled=0#page1</li>
<li>查询交通违章（仅支持29个省市）：http://m.46644.com/illegal/allcity.php</li>
<li>查询交通违章（广东备用1）：http://210.76.69.58/wfcx/query.jsp</li>
<li>查询交通违章（广东备用2）：【主用网址1】【备用网址2】</li>
<li>查询交通违章代码：http://m.46644.com/illegal/beijing/rule/</li>
<li>查询银行卡归属地（1）：http://3g.yinhangkahao.com/</li>
<li>查询银行卡归属地（2）：http://bank.niuchaxun.com/</li>
<li>银联卡号交易消费查询：https://www.95516.com/static/union/pages/order/search.html</li>
<li>查询全国列车时刻表：http://qq.ip138.com/train/</li>
<li>查询世界各国货币转换：http://qq.ip138.com/hl.asp?q=100</li>
<li>查询全国各地车牌（1）：http://www.ip138.com/carlist.htm</li>
<li>查询全国各地车牌（2）：http://chepai.niuchaxun.com/</li>
<li>查询购买国内机票：http://www.ip138.com/jb.htm</li>
<li>全球航班实时飞行图：https://www.flightradar24.com/</li>
<li>中国航班实时飞行图：http://www.airtu.com/FlightMap/FlightMap.html</li>
<li>查询邮政编码（1）：http://www.youbianku.com/</li>
<li>查询邮政编码（2）：http://youbian.niuchaxun.com/</li>
<li>查询地区区号：【区号查询地名】/【地名查询区号】</li>
<li>查询汉字拼音：http://qq.ip138.com/wb/wb.asp</li>
<li>查询同姓同名：http://zhaoren.idtag.cn/samename/searchName!searchIndex.htm</li>
<li>查询快递进度：http://www.kuaidi100.com/</li>
<li>度衡量计量单位换算转换器： http://qq.ip138.com/converter.htm</li>
<li>查询淘宝买家/卖家信誉：http://www.2cha.com/credit/credit_nick_.html</li>
<li>查询反义词变换：http://fyc.5156edu.com/</li>
<li>在线地球天气：https://www.windyty.com/</li>
<li>在线中央台风网：【官方网站1】【官方网站2】</li>
<li>在线天气卫星地图（中国区）：http://www.nmc.cn/publish/satellite/fy2.htm</li>
<li>在线天气卫星地图（大洋洲区）：http://himawari8.nict.go.jp/</li>
<li>在线检测FLASH版本：http://www.whatismyflashplayerversion.com/</li>
<li>在线检测JAVA版本：http://java.com/zh_CN/download/installed8.jsp</li>
<li>中国电信在线人工客服：http://im.ct10000.com/webclient/index</li>
<li>中国联通在线人工客服：http://inf.10010.com/serviceOnline/mobileServiceOnline/chat.do?accessType=01507&amp;needRobot=1</li>
<li>宽带快捷排障（大陆各地区电信）：http://wx.xmt.189.cn:8080/WX_CUST_WEBSERVICE/broadbandexclude/broadbandExcludeAction.do?action=toPage&amp;openid=kKHNXZZ3ntIiqvLzGxOo0Ye6FWdowO/RNRrDPBAwiqI=&amp;</li>
<li>宽带快捷排障+便捷服务（广东电信）：http://im.189.cn/xmt/net/index.do?subscribe=true&amp;status=ok&amp;openid=oBBmBjr8bwquNetqAehO_Jwt3_u0</li>
<li>检测是否IPV6：http://www.kame.net/</li>
<li>百度云网盘搜索（1）：http://www.oubear.com/</li>
<li>百度云网盘搜索（2）：http://m.sobaidupan.com/</li>
<li>百度云网盘搜索（3）：http://www.sosuopan.com/</li>
<li>百度云网盘搜索（4）：http://99baiduyun.com/</li>
<li>百度云网盘搜索（5）：http://www.xalssy.com.cn/</li>
<li>网盘搜索查询（1）：http://www.xilinjie.com/</li>
<li>网盘搜索查询（2）：http://www.panc.cc/</li>
<li>网盘搜索查询（3）：http://www.bdysou.com/</li>
<li>网盘搜索查询（4）：http://www.goutouying.com/</li>
<li>网盘搜索查询（5）：http://wangpan007.com/</li>
<li>网盘搜索查询（6）：http://www.daysou.com/</li>
<li>网盘搜索查询（7）：http://www.quzhuanpan.com/</li>
<li>网盘搜索查询（8）：http://md5.daimugua.com/</li>
<li>喵搜动漫资源网盘：【备用网址1】【备用网址2】</li>
<li>光影电影磁力下载：http://www.etdown.net/</li>
<li>BT磁力链接资源搜索（1）：http://www.btwhat.net/</li>
<li>BT磁力链接资源搜索（2）：http://www.ciliyun.net/</li>
<li>BT磁力链接资源搜索（3）：http://www.cilimao.me/</li>
<li>BT磁力链接资源搜索（4）：http://ciliba.net/</li>
<li>BT磁力链接资源搜索（5）：【官方网站1】【★官方网站2】</li>
<li>BT磁力链接资源搜索（6）：http://www.btcherry.info/</li>
<li>BT磁力链接资源搜索（7）：http://www.btrabbit.com/</li>
<li>BT磁力链接资源搜索（8）：http://www.youkubt.com/</li>
<li>BT磁力链接资源搜索（9）：https://591mov.com/zh-hans/</li>
<li>BT磁力链接资源搜索（10）：http://www.btsj5.com/</li>
<li>岭南通/广佛通查询余额：http://www.fsjtk.com/wx/yue.php</li>
<li>岭南通/羊城通 查询余额（beta）：http://weixin.gzyct.com/busiqry/user-card-balance!otherBalanceQry.action?openid=oKYOJjmESPF8pWm7rcPk63tA7oak&amp;cardno=输入车卡卡号</li>
<li>羊城通应用范围查询：http://weixin.gzyct.com/cpuqry/cpuqry.action?openid=oKYOJjmESPF8pWm7rcPk63tA7oak</li>
<li>腾讯QQ联系人头像查看和下载（1）：http://www.3464.com/Tools/GetQQFace/</li>
<li>腾讯QQ联系人头像查看和下载（2）：http://www.feifeiboke.com/tool/qqtx.html</li>
<li>腾讯QQ联系人头像查看和下载（3）：http://www.koukoucha.com/tool/qqtouxiang/</li>
<li>腾讯QQ联系人头像查看和下载（4）：http://www.dcqzone.com/qq/tx/</li>
<li>腾讯QQ头像/QQ空间头像查询和下载：http://momo8.com/tools/qqtouxiang/</li>
<li>QQ价值评估：http://www.atool.org/qq.php</li>
<li>360中国网络诈骗地图：http://vis.360.cn/open/fishsite</li>
<li>NORSE网络攻击地图：http://map.norsecorp.com/</li>
<li>卡巴斯基网络攻击地图：https://cybermap.kaspersky.com/</li>
<li>货币汇率查询：http://huilv.niuchaxun.com/</li>
<li>电费计算器：http://dianfei.niuchaxun.com/</li>
<li>每日油价查询（国内）：http://youjia.niuchaxun.com/</li>
<li>世界时差查询：http://shicha.niuchaxun.com/</li>
<li>查询地铁路线（大陆+台湾香港）：http://map.baidu.com/subways/</li>
<li>电脑系统进程查询：http://process.niuchaxun.com/</li>
<li>全球被黑站点统计：http://www.hack-cn.com/archive</li>
<li>检测浏览器内核版本：http://liulanmi.com/labs/core.html</li>
<li>检测浏览器版本号：https://aboutmybrowser.com/r5v01nyZ</li>
<li>查询QQ好友空间背景音乐（1）：http://www.koukoucha.com/music/</li>
<li>查询QQ好友空间背景音乐（2）：https://www.feifeiboke.com/qqmusic/</li>
<li>检测图片是否被PS：http://fotoforensics.com/</li>
<li>莆田系医院分布图：https://wandergis.com/hospital-viz/index.htm</li>
<li>★Google缓存网页快照大全：http://cachedview.com/index.php?lang=zh#</li>
<li>百度云分享失效重链：http://pan.baidu.com/share/home?uk=输入分享失效数字</li>
<li>佛山实时公交在线查询：http://www.oooxo.com/</li>
<li>12306帐号泄露查询：http://www.atool.org/12306.php</li>
<li>账号密码泄露查询（1）：https://qq.mima.re/</li>
<li>账号密码泄露查询（2）：https://haveibeenpwned.com/</li>
<li>在线屏幕测试：http://pingmu.zh-ang.com/</li>
<li>显示屏分辨率检测：http://www.3464.com/tools/DisplayResolution/</li>
<li>LOL英雄联盟查询助手：http://vip.ihuan.me/lol.htm</li>
<li>查询手机IMEI码信息：http://www.imei8.net/</li>
<li>在线识别音乐歌名（beta）：http://www.mooma.sh/</li>
<li>“车来了”网页版：【蓝色版】【绿色版】</li>
<li>在线接收手机短信（国外号码1）：http://receivefreesms.com/</li>
<li>在线接收手机短信（国外号码2）：【备用网址1】【备用网址2】【备用网址3】</li>
<li>在线识别动漫图（1）：http://saucenao.com/</li>
<li>在线识别动漫图（2）：https://pic.nyaso.com/search.html</li>
<li>特殊符号大全：http://cn.piliapp.com/symbol/</li>
<li>微博图片反查（1）：http://wbimg.huyuaning.com/</li>
<li>微博图片反查（2）：http://www.sq520.net/weibo-fancha/</li>
<li>微博图片反查（3）：https://toolmao.com/tool/img2weibo/</li>
<li>微博图片反查（4）：https://weibo.2333.me/</li>
<li>在线免费代理IP：https://ip.ihuan.me/</li>
</ol>
<hr>
<ul>
<li>
<h3 id="在线工具网站" tabindex="-1"><a class="header-anchor" href="#在线工具网站" aria-hidden="true">#</a> 在线工具网站</h3>
</li>
</ul>
<hr>
<ol>
<li>在线工具大全：http://tool.oschina.net/</li>
<li>在线视频/图片/音频/文件转换工具：http://www.fileconverto.com/</li>
<li>中国大陆身份证大全（1）：http://shenfenzheng.293.net/</li>
<li>中国大陆身份证大全（2）：http://idcard.niuchaxun.com/</li>
<li>中国大陆身份证大全（3）：http://tool7001.com/</li>
<li>10个国家身份生成：http://www.haoweichi.com/</li>
<li>在线photoshop：http://www.webps.cn/</li>
<li>在线百度word：http://word.baidu.com/</li>
<li>★在线谷歌office：https://www.google.cn/intl/zh-CN/docs/about/</li>
<li>在线微软office：https://www.office.com/</li>
<li>在线txt记事本：【官方网站1】【官方网站2】</li>
<li>在线电话轰炸机：【呼之官网1】【呼之官网2】【呼之官网3】</li>
<li>在线短信轰炸机（1）：http://zha.vvoso.com/</li>
<li>在线短信轰炸机（2）：http://tools.wx6.org/duanxinhongzhaji/</li>
<li>在线短信轰炸机（3）：http://www.5c5x.com/hzj/</li>
<li>在线短信轰炸机（4）：http://peng3.com/sms/ 【验证码：ydjy】</li>
<li>在线短信轰炸机（5）：http://eateat.net/</li>
<li>在线短信轰炸机（6）：http://sms.in0.cc/</li>
<li>在线短信轰炸机（7）：【普通模式】【迷你模式】【无敌模式】</li>
<li>在线短信轰炸机（8）：http://zgtv.spo38.igeek.gq/aip/</li>
<li>在线短信轰炸机（9）：http://zhilmw.go4c.arebz.co/dx/index.php</li>
<li>在线装逼（1）：http://deepba.com/</li>
<li>在线装逼（2）：http://www.zhuangbi.info/</li>
<li>ZeroNet在线代理访问：https://zero.acelewis.com/</li>
<li>在线代理IP：https://proxy.coderbusy.com/zh-cn</li>
<li>在线代理（1）：https://sg1.mm.4night.win:991/index.php</li>
<li>在线代理（2）：https://r.t.renren2017.com/</li>
<li>在线代理（3）：http://www.youbiyao.net/</li>
<li>在线代理（4）：https://idaili.club/</li>
<li>在线代理（5）：http://sosovo.com/</li>
<li>在线代理（6）：【备用网址1】【备用网址2】【备用网址3】</li>
<li>在线查找病毒（1）：http://www.virscan.org/</li>
<li>在线查找病毒（2）：https://virusscan.jotti.org/</li>
<li>在线查找病毒（3）：https://www.virustotal.com/zh-cn/</li>
<li>在线查询病毒（4）：http://habo.qq.com/</li>
<li>在线查询病毒（5）：http://scan.shouji.360.cn/</li>
<li>在线查询病毒（6）：http://m.qq.com/security_lab/scans_online.jsp</li>
<li>在线查询病毒（7）：https://x.threatbook.cn/</li>
<li>在线查询病毒（8）：http://online.drweb.com/</li>
<li>金山毒霸网络版（行业专用版）：http://210.45.224.52:6868/</li>
<li>网站安全查询（1）：http://webscan.360.cn/</li>
<li>网站安全查询（2）：http://onlinelinkscan.com/</li>
<li>网站安全查询（3）：【中国版本】【俄罗斯版本】</li>
<li>网站安全查询（4）：https://app.webinspector.com/</li>
<li>在线短网址还原（1）：http://dwz.aidmin.cn/restore.php</li>
<li>在线短网址还原（2）：http://baidu.nu/index.php?m=public&amp;a=reurl</li>
<li>在线短网址还原（3）：http://duanwangzhihuanyuan.51240.com/</li>
<li>在线短网址大全（1）：【备用网址1】【备用网址2】</li>
<li>在线短网址大全（2）：http://www.ft12.com/</li>
<li>在线短网址大全（3）：https://goo.gd/</li>
<li>在线短网址大全（4）：【备用网址1】【备用网址2】</li>
<li>dwz.mn短网址：http://www.dwz.mn/</li>
<li>百度短网址：http://dwz.cn/</li>
<li>冰枫短网址：https://ibf.tw/</li>
<li>新浪微博短网址（1）：http://www.atool.org/shorturl.php</li>
<li>新浪微博短网址（2）：http://surl.sinaapp.com/</li>
<li>缩我短网址：http://suo.im/</li>
<li>硬是要缩短网址：https://4fun.tw/</li>
<li>980.so短网址：http://980.so/</li>
<li>RRD短网址：http://rrd.me/</li>
<li>佳鑫短网址：http://x28.me/</li>
<li>i-to短网址：http://i-to.cc/</li>
<li>晨旭长网址：http://biubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiubiu.com/index.html</li>
<li>随机1小时VPN：http://my.0ff0.net/</li>
<li>随机24小时PAC：https://freepac.co/</li>
<li>随机24小时SS：http://freess.org/</li>
<li>DDOS网页端（1）：http://quezstresser.com/</li>
<li>DDOS网页端（2）：http://orcahub.com/</li>
<li>在线网络电视（1）：http://www.shiting5.com/hd/</li>
<li>在线网络电视（2）：http://www.shiting5.com/tv/cn/cctv/</li>
<li>在线网络电视（3）：http://tv.shebao5.com/</li>
<li>在线网络电视（4）：http://zb.dsqndh.com/【仅支持手机浏览器带视频播放器】</li>
<li>在线网络电视（全球1）：【英文版】【中文版】</li>
<li>在线网络电视（全球2）：http://tvopedia.com/</li>
<li>在线网络电视（全球3）：http://rushplayer.com/wapstream.aspx?v=1.54&amp;t=2&amp;g=282&amp;app=1000【仅支持手机浏览器带视频播放器】</li>
<li>在线网络电视（港澳台+韩国）：http://www.cietv.com/images/img/100/</li>
<li>在线网络电视（央视+各省卫视）：http://ivi.bupt.edu.cn/</li>
<li>在线JSON数据解析器：http://www.toolmao.com/json-parser-jiexi</li>
<li>在线免费打电话（1）：http://ievaphone.com/</li>
<li>在线免费打电话（2）：https://call2friends.com/</li>
<li>在线免费打电话（3）【限制13个国家】：http://makefreecallsonline.com/countries.php</li>
<li>在线免费发短信（1）：http://www.afreesms.com/</li>
<li>在线免费发短信（2）：http://sendsmsonlineforfree.com/countries.php</li>
<li>在线免费发短信（3）【限制英文】：https://globfone.com/sms/</li>
<li>在线免费发短信（4）：http://www.socialland.net/sendsms.php</li>
<li>在线图片上传大全：http://upload.otar.im/</li>
<li>微博图床上传（1）：http://pic.xiaojianjian.net/</li>
<li>微博图床上传（2）：http://tool.mkblog.cn/tuchuang/</li>
<li>在线图片上传（1）：http://chuantu.biz/</li>
<li>在线图片上传（2）：【官方新版】【官方旧版】</li>
<li>在线图片上传（3）：http://www.tietuku.com/upload</li>
<li>在线图片上传（4）：http://tw.picwindow.com/</li>
<li>在线图片上传（5）：http://www.wailian.work/</li>
<li>在线图片上传（6）：https://img.vim-cn.com/</li>
<li>在线图片上传（7）：http://upload.ouliu.net/</li>
<li>在线图片上传（8）：https://sm.ms/</li>
<li>在线图片上传（9）：https://ooxx.ooo/upload</li>
<li>在线图片上传（10）：https://pic.tink.im/</li>
<li>在线图片上传（11）：http://ih.pwcong.xyz:8080/</li>
<li>在线图片上传（12）：https://img.fghrsh.net/</li>
<li>在线压缩图片（1）：http://zhitu.isux.us/</li>
<li>在线压缩图片（2）：http://www.atool.org/pngcompression.php</li>
<li>在线音乐上传（1）：http://up.jqzone.com/</li>
<li>在线音乐上传（2）：http://picosong.com/</li>
<li>在线音乐上传（3）：http://tianyan999.com/user/up.php</li>
<li>音乐查询和在线播放（1）：https://music.liuli.lol/</li>
<li>音乐查询和在线播放（2）：http://music.2333.me/</li>
<li>音乐查询和在线播放（3）：http://music.ifkdy.com/</li>
<li>音乐查询和在线播放（4）：http://music.xrbk.top/</li>
<li>音乐查询和在线播放（5）：https://www.wlhrt.cn/tool/mp3/</li>
<li>音乐查询和在线播放（6）：http://www.liumingye.cn/tools/music/</li>
<li>音乐查询和在线播放（7）：http://mp3.vsucai.cn/</li>
<li>在线音乐下载（1）：http://music.dsqndh.com/</li>
<li>在线音乐下载（2）：http://music.cn.tn/</li>
<li>VR全景拍摄：http://720yun.com/</li>
<li>360水滴摄像头直播：http://jia.360.cn/pc/</li>
<li>百度云摄像头直播：http://kankan.baidu.com/</li>
<li>萤石摄像头直播：http://square.ys7.com/index</li>
<li>爱耳目摄像头直播：http://www.iermu.com/zhibo</li>
<li>Viewerframe摄像头：http://webcams.gosnippy.com/</li>
<li>★全球网络IP摄像头直播：http://www.insecam.org/</li>
<li>Youtube音乐下载：http://i-dl.net/</li>
<li>Youtube视频转换工具（1）：http://2conv.com/cn/</li>
<li>Youtube视频转换工具（2）：https://savemedia.com/</li>
<li>Youtube视频转换工具（3）：http://tw.getv-go.com/</li>
<li>Youtube视频转换工具（4）：http://www.dirpy.com/</li>
<li>Youtube视频转换工具（5）：https://y2mate.com/zh-cn/</li>
<li>新浪微博视频解析转换工具：http://www.weibovideo.com/</li>
<li>bilibili哔哩哔哩视频解析转换工具（1）：http://www.ibilibili.com/</li>
<li>bilibili哔哩哔哩视频解析转换工具（2）：http://www.bilibilijj.com/</li>
<li>国内视频解析转换工具（1）：【电信线路用户】【联通线路用户】</li>
<li>国内视频解析转换工具（2）：http://www.flvcd.com/index.htm</li>
<li>国内视频解析转换工具（3）：http://www.shokdown.com/</li>
<li>国内下载地址解析转换工具（1）：http://xiazaidizhi.niuchaxun.com/</li>
<li>国内下载地址解析转换工具（2）：http://www.iqshw.com/url/</li>
<li>国内下载地址解析转换工具（3）：http://tool.114la.com/code/urlconvert/</li>
<li>国内下载地址解析转换工具（4）：https://591mov.com/zh-hans/url_trans/</li>
<li>在线播放VIP会员电影视频（1）：http://www.liumingye.cn/tools/video/</li>
<li>在线播放VIP会员电影视频（2）：http://v.laod.cn/</li>
<li>在线播放VIP会员电影视频（3）：http://tv.dsqndh.com/</li>
<li>在线播放VIP会员电影视频（4）：http://guikea.cn/vpj/index.html</li>
<li>在线播放VIP会员电影视频（5）：https://www.dujin.org/video/</li>
<li>在线播放VIP会员电影视频（6）：http://zwyqzd.czqin.com/jxa/vip.php</li>
<li>在线播放VIP会员电影视频（7）：http://www.chepeijian.cn/jiexi.html</li>
<li>在线播放VIP会员电影视频（8）：【备用网址1】【备用网址2】【备用网址3】</li>
<li>在线播放VIP会员电影视频（输入C值）：【备用网址1】【备用网址2】</li>
<li>在线BT种子链接磁力云播放（1）：http://apiv.ga/magnet/</li>
<li>在线BT种子链接磁力云播放（2）：http://www.aisiyunbo.xyz/magnetGet.html</li>
<li>种子转换磁力链接（1）：https://www.torrentkitty.tv/</li>
<li>种子转换磁力链接（2）：http://www.torrent.org.cn/</li>
<li>虚假磁链生成器：http://bt.papapoi.com/</li>
<li>在线百度输入法（1）：http://shurufa.niuchaxun.com/</li>
<li>在线谷歌输入法（2）：http://www.google.cn/inputtools/try/</li>
<li>在线计算器（1）：http://jisuanqi.niuchaxun.com/</li>
<li>在线计算机（2）：http://tool.114la.com/code/jisuanqi/</li>
<li>在线火星文转换：http://huoxingwen.niuchaxun.com/</li>
<li>在线拆字工具：http://chaizi.niuchaxun.com/</li>
<li>在线mp3音乐外链地址（1）：http://www.haoduoge.com/</li>
<li>在线mp3音乐外链地址（2）：http://www.111ttt.com/up/</li>
<li>在线mp3音乐外链地址（3）：http://94001.com/</li>
<li>在线mp3音乐外链地址（4）：http://www.xuenb.com/tools/mp3/</li>
<li>在线mp3音乐外链地址（5）：http://zwyqzd.czqin.com/jxa/mp3.php</li>
<li>二维码生成器：http://www.3464.com/tools/QrcodeMaster/</li>
<li>二维码生成器大全（1）：http://www.34qr.com/</li>
<li>二维码生成器大全（2）：http://www.wwei.cn/</li>
<li>二维码生成器大全（3）：http://www.qrstuff.com/</li>
<li>二维码生成器大全（4）：https://charlie.qrcreate.h5.ersansan.cn/</li>
<li>生成微信群用就二维码：https://yongjiuma.com/</li>
<li>草料二维码扫描器：https://cli.im/deqr</li>
<li>在线倒计时：http://xxhd.net.cn/</li>
<li>在线制作GIF：http://www.gif5.net/</li>
<li>在线LOGO制作：http://www.logowu.com/</li>
<li>在线制作DJ电台：http://www.partycloud.fm/</li>
<li>在线Google+头像产生器：http://gplus.orinx.com/</li>
<li>谷歌APK下载器：https://apps.evozi.com/apk-downloader/</li>
<li>在线制作圣诞头像：http://xmas.noapp.net/AvatarMaker.aspx</li>
<li>在线解压文件：http://www.wobzip.org/</li>
<li>在线文件上传（1）：https://userscloud.com/</li>
<li>在线文件上传（2）：https://bitsend.jp/</li>
<li>在线文件上传（3）：http://www.72blog.com/tu/</li>
<li>在线种子上传：http://www.360xixi.com/</li>
<li>各种在线翻译：http://qq.ip138.com/tran.htm</li>
<li>在线各卫星看地球：http://www.flashearth.com/</li>
<li>在线检测电脑配置：http://test.mydrivers.com/install.htm</li>
<li>在线手机性价检测：http://www.3464.com/tools/MPPTesting/test.asp【仅支持QQ浏览器和UC浏览器】</li>
<li>在线测网速（1）：http://wangsu.niuchaxun.com/</li>
<li>在线测网速（2）：http://tool.114la.com/live/speed/</li>
<li>在线测网速（3）：http://www.kmguolv.com/cesu/</li>
<li>在线测网速（4）：http://wangsu.baishicha.com/</li>
<li>在线测网速：【中国移动】【中国联通】【中国电信(新)】【中国电信(旧)】【香港宽频（旧）】【香港宽频（新）】【台湾宽频】</li>
<li>网站站长查询（1）：http://www.webmasterhome.cn/</li>
<li>网站站长查询（2）：http://www.17ce.com/</li>
<li>网站站长查询（3）：http://tool.chinaz.com/</li>
<li>网站站长查询（4）：http://www.super-ping.com/sc.html</li>
<li>网站站长查询（5）：https://asm.ca.com/zh_cn/ping.php</li>
<li>腾讯QQ第三方授权管理：http://connect.qq.com/toc/auth_manager</li>
<li>腾讯QQ联系人恢复系统：http://huifu.qq.com/</li>
<li>腾讯增值服务停用关闭：https://kf.qq.com/touch/mobileqq/service_cancel.html</li>
<li>检测密码强度（1）：http://mima.niuchaxun.com/</li>
<li>检测密码强度（2）：https://howsecureismypassword.net</li>
<li>检测浏览器1（Javascript 性能）：【★谷歌v8版】【SunSpider版】</li>
<li>检测浏览器2（RoboHornet Pro测试）：【微软fishbowl】【微软FishIETank】</li>
<li>检测浏览器3（Peacekeeper 测试）：http://peacekeeper.futuremark.com/run.action</li>
<li>检测浏览器4（HTML5相关测试）：http://html5test.com/</li>
<li>★检测APK在线签名校验：https://apkpure.com/apk-signature-verification</li>
<li>在线安卓软件反编译：http://www.javadecompilers.com/apk</li>
<li>在线favicon.ico图标制作：http://www.atool.org/ico.php</li>
<li>在线获取网站favicon.ico图标：http://g.soz.im/输入完整URL网址</li>
<li>在线文字识别转换：http://ocr.wdku.net/</li>
<li>奇迹暖暖在线工具：http://seal100x.github.io/nikkiup2u3/</li>
<li>在线邮件发送（含文件）：https://www.send18.com/</li>
<li>在线制作绘图画稿（画画）：http://kokuban.in/mypage/draw/skeb</li>
<li>在线听大暴雨声音：http://raining.fm/</li>
<li>PDF文件转换和编辑：https://lightpdf.com/zh/</li>
<li>微信公众平台内容编辑器：http://wx.atool.org/</li>
<li>加密解密摩斯密码：http://www.atool.org/morse.php</li>
<li>QQ空间写说说代码生成：http://tool.vvoso.com/tool/kjdm/</li>
<li>QQ消息撤回名片生成（QQ群名片反字）：http://qun.vvoso.com/</li>
<li>在线摄像头自拍：https://webcamtoy.com/zh/</li>
<li>自定义QQ分享生成器：http://qqshare.papapoi.com/</li>
<li>在线超级SEO外链工具：http://seo.dmeng.net/</li>
<li>QQ反向名字生成器：http://qq.papapoi.com/</li>
<li>在线QQ空间说说刷赞：http://ssz.lxzan.com/</li>
<li>【YOPmail】临时邮箱（1）：【@yopmail.com官网】【@yopmail.fr官网】</li>
<li>【TempMail】临时邮箱（2）：https://temp-mail.org/zh/</li>
<li>10分钟临时邮箱（3）：【电脑版】【手机版】</li>
<li>10分钟临时邮箱（4）：【@bccto.me邮箱】【@mail.bccto.me邮箱】</li>
<li>【查错网】临时邮箱（5）：http://24mail.chacuo.net/</li>
<li>在线伪造邮件邮箱发送（1）：http://tool.chacuo.net/mailanonymous</li>
<li>在线伪造邮件邮箱发送（2）：https://ihuan.me/mail</li>
<li>在线匿名邮件发送：http://tool.chacuo.net/mailsend</li>
<li>在线百度关键字搜索生成：https://buhuibaidu.me/</li>
<li>在线生成圣诞帽头像：http://hat.svvme.com/</li>
<li>在线微信支付宝收款码合成：http://heyfox.herokuapp.com/</li>
<li>在线腾讯人工QQ客服：http://crm2.qq.com/page/portalpage/wpa.php?%20uin=40012345&amp;f=1&amp;ty=1&amp;ap=000011:400793:|m:13|f:KFXD37x</li>
<li>美图秀秀批处理图片：http://xiuxiu.web.meitu.com/plugin/batch/taobao.html</li>
</ol>
<hr>
<ul>
<li>在线福利和良心网站</li>
</ul>
<hr>
<ol>
<li>免费申请支付宝收钱码：https://b.alipay.com/settling/tc/entry.htm</li>
<li>会员分享网（1）：http://www.fenxiangdashi.com/</li>
<li>会员分享网（2）：http://www.123huodong.com/zhanghaofenxiang/</li>
<li>会员分享网（3）：http://www.hot3000.com/</li>
<li>会员分享网（4）：http://www.vipzhanghao.com/</li>
<li>会员分享网（5）：http://www.xlcun.com/</li>
<li>会员分享网（6）：http://vip.ihuan.me/</li>
<li>会员分享网（7）：http://www.zhanghaofen.com/</li>
<li>迅雷会员分享（1）：http://www.jxaxs.com/xunlei/</li>
<li>迅雷会员分享（2）：http://www.521xunlei.com/</li>
<li>迅雷会员分享（3）：http://www.wantsee.cn/</li>
<li>迅雷会员分享（4）：http://xlfans.com/</li>
<li>迅雷会员分享（5）：http://www.laobinggun.com/forum-37-1.html</li>
<li>迅雷会员分享（6）：http://www.fenxs.com/category/gongxiang</li>
<li>迅雷会员分享（7）：http://www.xunleihuiyuan.net/vip/</li>
<li>爱奇艺会员分享（1）：http://www.zqnf.com/iqiyimianfeihuiyuan.htm</li>
<li>爱奇艺会员分享（2）：http://myvipbbs.com/forum-2-1.html</li>
<li>爱奇艺会员分享（3）：http://www.fenxiangdashi.com/aiqiyi/</li>
<li>优酷土豆会员分享：http://www.vipdage.com/</li>
<li>115会员分享网：http://in115.com/</li>
<li>在线黑白图标：http://iconmonstr.com/</li>
<li>在线图标Logo大全：http://megaicons.net/</li>
<li>特别安卓软件（1）：http://onlineapk.com/</li>
<li>APKPure下载谷歌商店软件：【com域名中文版网站】【com域名中文版谷歌APK下载器】【co域名网站】【co域名谷歌APK下载器】</li>
<li>APKSum下载谷歌商店软件：https://www.apksum.com/</li>
<li>第三方苹果商店APP下载：https://www.appaddict.org/</li>
<li>zd423优化软件：http://www.zdfans.com/</li>
<li>919PT特别软件：http://www.919pt.com/</li>
<li>Crx4Chrome扩展程序：http://www.crx4chrome.com/</li>
<li>谷歌扩展程序下载器（1）：http://chrome-extension-downloader.com/</li>
<li>谷歌扩展程序下载器（2）：http://crx.2333.me/</li>
<li>谷歌APK软件下载器（1）：https://apps.evozi.com/apk-downloader/</li>
<li>谷歌APK软件下载器（2）：https://androidappsapk.co/apkdownloader/</li>
<li>★谷歌地球背景壁纸：http://earthview.withgoogle.com/</li>
<li>赛风psiphon（官方）：【备用官网1】【备用官网2】</li>
<li>蓝灯lantern（github）：【电脑版下载】【安卓版下载】</li>
<li>官方ROM（1）：http://www.cnroms.com/</li>
<li>官方ROM（2）：http://www.sxrom.com/</li>
<li>官方ROM（3）：http://www.muzisoft.com/roms/</li>
<li>MSDN，我告诉你：http://www.itellyou.cn/</li>
<li>二次元动漫：http://www.2animx.com/</li>
<li>Omegle在线陌生人聊天：http://www.omegle.com/</li>
<li>触宝电话国际长途邀请码：http://dialer-cdn.cootekservice.com/dialer/free-call/international/invitation_code/index.html?plg_nld=1&amp;plg_uin=1&amp;plg_auth=1&amp;plg_nld=1&amp;plg_usr=1&amp;plg_vkey=1&amp;plg_dev=1&amp;from=groupmessage&amp;isappinstalled=0</li>
<li>中国联通手机营业厅：https://m.10010.com</li>
<li>中国联通一起沃：【登录入口】【每日签到流量】【每日领流量红包】</li>
<li>中国联通“免费网龄升级计划”：http://iservice.10010.com/e4/transact/basic/net_age_iframe.html</li>
<li>盛天网盘（国内）：http://pan.stnts.com/【Ps：这里注册再互送20GB永久空间！！！】</li>
<li>pCloud云盘（国外）：https://my.pcloud.com/</li>
<li>中国版Youtube海外视频：https://www.fantasy.tv/</li>
<li>在线YY4480高清影院（1）：【官网网址1】【备用网址2】【备用网址3】</li>
<li>在线爱看高清影院（2）：【官网网址1】【备用网址2】</li>
<li>萌人物电影电视剧大片网（1）：http://www.mrenwu.com/</li>
<li>酷播网电影电视剧大片网（2）：http://www.kb20.cc/</li>
<li>9080电影电视剧大片网（3）：http://www.9080dy.com/</li>
<li>有家影院电影电视剧大片网（4）：http://www.youjiady.com/</li>
<li>牛B四十电影电视剧大片网（5）：http://www.nb40.com/</li>
<li>80手机电影电视剧大片网（6）：http://www.80s.tw/</li>
<li>大猫电影电视剧大片网（7）：http://www.h6080.com/</li>
<li>琪琪看片电影电视剧大片网（8）：http://www.77kp.com/</li>
<li>影视大片电影电视剧大片网（9）：http://www.yingshidaquan.cc/</li>
<li>神马影院电影电视剧大片网（10）：http://www.ilaoziys.com/</li>
<li>网盘相册笔记大全：http://www.benpig.com/photo.htm</li>
<li>FUN DNS：http://www.fundns.cn/</li>
</ol>
</template>
