<template><h1 id="openssl一键自签证书" tabindex="-1"><a class="header-anchor" href="#openssl一键自签证书" aria-hidden="true">#</a> Openssl一键自签证书</h1>
<p><code>vim openssl.sh</code></p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token shebang important">#!/bin/bash</span>
<span class="token keyword">while</span> <span class="token punctuation">[</span><span class="token punctuation">[</span> -z <span class="token string">"<span class="token variable">$domain</span>"</span> <span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">;</span><span class="token keyword">do</span>
    <span class="token builtin class-name">read</span> -p <span class="token string">"输入域名/IP(必填,如 *.haoduck.com): "</span> domain
<span class="token keyword">done</span>
<span class="token builtin class-name">read</span> -p <span class="token string">"输入邮箱(选填,默认admin@haoduck.com): "</span> mail
<span class="token punctuation">[</span><span class="token punctuation">[</span> -z <span class="token string">"<span class="token variable">$mail</span>"</span> <span class="token punctuation">]</span><span class="token punctuation">]</span> <span class="token operator">&amp;&amp;</span> <span class="token assign-left variable">mail</span><span class="token operator">=</span>admin@haoduck.com
<span class="token builtin class-name">read</span> -p <span class="token string">"输入日期(选填,默认3650): "</span> day
<span class="token punctuation">[</span><span class="token punctuation">[</span> -z <span class="token string">"<span class="token variable">$day</span>"</span> <span class="token punctuation">]</span><span class="token punctuation">]</span> <span class="token operator">&amp;&amp;</span> <span class="token assign-left variable">day</span><span class="token operator">=</span><span class="token number">3650</span>
<span class="token assign-left variable">dir</span><span class="token operator">=</span><span class="token variable">$domain</span> <span class="token operator">&amp;&amp;</span> <span class="token function">mkdir</span> -p <span class="token variable">$dir</span>
<span class="token assign-left variable">crt_file</span><span class="token operator">=</span><span class="token string">"<span class="token variable">$dir</span>/<span class="token variable">${domain}</span>.crt"</span>
<span class="token assign-left variable">key_file</span><span class="token operator">=</span><span class="token string">"<span class="token variable">$dir</span>/<span class="token variable">${domain}</span>.key"</span>
<span class="token keyword">if</span> <span class="token punctuation">[</span><span class="token punctuation">[</span> <span class="token string">"<span class="token variable"><span class="token variable">$(</span><span class="token builtin class-name">command</span> -v openssl<span class="token variable">)</span></span>"</span> <span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">;</span><span class="token keyword">then</span>
    openssl req -x509 -nodes -newkey rsa:2048 -days <span class="token variable">$day</span> -keyout <span class="token variable">$key_file</span> -out <span class="token variable">$crt_file</span> -subj <span class="token string">"/C=US/ST=California/L=Los Angeles/O=Haoduck/OU=Aoao/CN=<span class="token variable">${domain}</span>/emailAddress=<span class="token variable">${mail}</span>"</span>
    <span class="token builtin class-name">echo</span> -e <span class="token string">"<span class="token entity" title="\t">\t</span>证书：<span class="token variable"><span class="token variable">$(</span><span class="token builtin class-name">pwd</span><span class="token variable">)</span></span>/<span class="token variable">$crt_file</span><span class="token entity" title="\n">\n</span><span class="token entity" title="\t">\t</span>私钥：<span class="token variable"><span class="token variable">$(</span><span class="token builtin class-name">pwd</span><span class="token variable">)</span></span>/<span class="token variable">$key_file</span>"</span>
<span class="token keyword">else</span>
    <span class="token builtin class-name">echo</span> <span class="token string">"openssl 未安装"</span>
<span class="token keyword">fi</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><p><code>bash openssl.sh</code></p>
</template>
